### ISSUE TITLE
Angular Chat UI Kit Usage

### ISSUE THREAD

**Issue by bilal-ahmed-dev** [cometchat-pro/cometchat-pro-angular-ui-kit#1]
Hello,

I have followed the instructions for this repository.
1 - Clone the repository
2 - Run npm install 
3 - Run npm install @cometchat-pro/chat@2.0.6 --save
4 - npm run build cometchat-angular-ui-kit

It will create the dist folder in angular-chat-ui-kit.
After this i am confused from here that how would i use the build library kit into wordpress theme.

Thanks

**Comment by priyadarshininadar** [comment]
It sounds like you'll be a great fit for our new Chat Widget Extension. The extension allows you to embed CometChat Pro using a simple copy/paste code. 
Here are the instructions:

1. Login to your CometChat Pro Dashboard (you can signup for free)
2. Select your app and visit the API Keys section to copy your Auth Key
3. Head to Extensions page and add the Chat Widget Extension
4. Click on the Installed tab and then the Settings for the Chat Widget Extension
5. Create a new widget and paste the Auth Key you copied earlier
6. Configure your new widget and then click on Settings button
7. Visit the Code tab and copy the code
8. Paste this code on your site (and modify the variables as per your needs)

If you are using WordPress, then:

1. Download our WordPress plugin
2. Watch this video tutorial
3. Use the following shortcode in your WordPress pages:
4. For a group- (change "supergroup" to the GUID you want to show)
5. [cometchat-pro widget-id="YOURWIDGETID" default-id="supergroup" default-type="group"]
6. For a user- (change "supergroup" to the UID you want to show)
7. [cometchat-pro widget-id="YOURWIDGETID" default-id="superhero1" default-type="user"]

Please let me know if you need any assistance.
