### ISSUE TITLE
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

### ISSUE THREAD

**Issue by caglarturkurka** [cometchat-pro/cometchat-pro-angular-ui-kit#10]
### Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

When I want to import cometchat-pro-chat-ui-kit to my project, I got Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
.
Please Could you tell me how can I solve this problem ? I removed all of BrowserModule from CometChat source code, but error is not solved.

My CometChat version is latest version "@cometchat-pro/chat": "^2.3.0",
My Project's Angular version is 8.2.14

**Comment by gaurav-chandra** [comment]
+1, I have removed browser module from the ui kit modules but still have this problem.

**Comment by gaurav-chandra** [comment]
Got it working. Along with BrowserModule, we have to remove BrowserAnimationModule also and move these 2 to app.module file if we use lazy loading. Checkout this explanation: [https://dev.to/sanketmaru/import-once-browser-module-1pie](https://dev.to/sanketmaru/import-once-browser-module-1pie)
