### ISSUE TITLE
Duplicate case statements in cometchat-messages.component.ts

### ISSUE THREAD

**Issue by mghijsen** [cometchat-pro/cometchat-pro-angular-ui-kit#9]
### Describe the problem

We're using this library in our application and because we have stricter typescript checking we noticed that a number of case statements in the actionHandler function in the cometchat-messages.component.ts are duplicated. The duplicate statements are on line numbers: 
236:17  error  Duplicate case label  no-duplicate-case
259:17  error  Duplicate case label  no-duplicate-case
260:17  error  Duplicate case label  no-duplicate-case
261:17  error  Duplicate case label  no-duplicate-case
262:17  error  Duplicate case label  no-duplicate-case 

At the moment the duplicated case statements trigger the same behaviour so there is no bug yet but the duplicated case statements might cause issues in the future.

Please let me know if you would like me to create a pull request.

### What was the expected behavior?

N/A

### Reproduction

N/A

### Environment

N/A

**Comment by ketanyekale** [comment]
Looks like this was missed. It had been fixed. For now, check our latest v4 UI Kits.
